version: '3.8'

services:
  itviec-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DATABASE_URL=${ITVIEC_DB_URI}
    volumes:
      - .:/app
      - /app/node_modules
